#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
MSG="System is going down..."

# We check for this file in stage3 to halt or reboot
touch /run/runit/reboot

# Proceed with shutdown process
echo "$MSG" | wall
